controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 2.0
  acc_lim_x: 2.0
  
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.1
  
  holonomic_robot: false
  dwa: true
  vx_samples: 6
  meter_scoring: true
