obstacle_range: 2.5
raytrace_range: 4.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
transform_tolerance: 10.0
robot_radius: 0.25
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera, data_type: LaserScan, topic: min_scan/scan, marking: true, clearing: true}
