obstacle_range: 2.5
raytrace_range: 4.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.25
inflation_radius: 0.1

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera, data_type: PointCloud2, topic: /pointcloud, marking: true, clearing: true}
